dv/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [
	url(r'^dv/$', index, name='dv'),
    # url(r'^contact/$', 'home.views.contact',name='contact'),

]

company/models.py
import uuid

from django.db import models

# Create your models here.
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import ugettext as _

from payment.models import Order
from payment.models import Event
from geoposition.fields import GeopositionField
from geoposition import Geoposition


class Businnes(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = models.ForeignKey('self',blank=True,null=True)
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255,default='fa fa-sitemap')
    image = models.ImageField('business/images',blank=True,null=True,max_length=500)
    cover = models.ImageField('business/cover',blank=True,null=True,max_length=500)
    order_index = models.IntegerField()
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "name__icontains",)
    def __str__(self):
        return self.name
    def get_parent_business(self):
        return Businnes.objects.filter(parent=self).filter(active=True).exclude(id=self.id).order_by('order_index')

    def get_company_count(self):
        return Company.objects.filter(Q(businnes_type=self) | Q(businnes_type__parent=self)).exclude(is_active=False,deleted=True).count()

    def get_own_company_count(self):
        return Company.objects.filter(businnes_type=self).exclude(is_active=False,deleted=True).count()

class Company(models.Model):
    id  = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='companies/logo',max_length=500)
    cover_photo = models.ImageField(upload_to='companies/cover-photo',blank=True,null=True,max_length=500)
    slogan = models.CharField(max_length=255,blank=True,null=True)
    email = models.EmailField()
    phones = models.CharField(max_length=255,blank=True,null=True)
    voen = models.CharField(max_length=255)
    bank_account = models.CharField(max_length=255) # ayrica cedvelde olmalidir
    region = models.ForeignKey('general.Region')
    address = models.CharField(max_length=255)
    businnes_type = models.ManyToManyField('Businnes')
    is_active = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    practices = models.TextField()
    profile = models.ForeignKey('registration.Profile')
    position = GeopositionField(blank=True,null=True)
    slug = models.SlugField(default='slug')
    date = models.DateTimeField(auto_now_add=True)
    def get_company_product_count(self):
        cps = CompanyProductOrService.objects.filter(company=self).filter(active=True).filter(deleted=False).count()
        return cps
    def get_event_count(self):
        ecs = Event.objects.filter(company=self).filter(is_active=True).filter(deleted=False).count()
        return ecs
    def __str__(self):
        return self.name
    def get_attachments(self):
        c_as = CompanyAttachment.objects.filter(company=self)
        return c_as

class CompanyAttachment(models.Model):
    company = models.ForeignKey('Company')
    file = models.FileField(upload_to='company/attachments',max_length=500)
    def __str__(self):
        return self.company.name


ProductOrServiceChoices = (
    ('product', _("product")),
    ('service', _("service")),
)

class CompanyProductOrService(models.Model):
    id  = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey('Company')
    type = models.CharField(max_length=50,choices=ProductOrServiceChoices,default='product')
    product_or_service = models.ForeignKey('ProductOrService')
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='companies/logo',max_length=500)
    slogan = models.CharField(max_length=255,blank=True,null=True)
    quantity = models.DecimalField(max_digits=19, decimal_places=5)
    price = models.DecimalField(max_digits=19, decimal_places=5)
    currency = models.ForeignKey('payment.Currency')
    description = models.TextField()
    businness_types = models.ManyToManyField('Businnes',blank=True,null=True)
    active = models.BooleanField()
    deleted = models.BooleanField(default=False)
    created_date = models.DateField(default=timezone.now())
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.name
    def get_company_products_services(self):
        cps = CompanyProductOrService.objects.filter(company=self.company).filter(active=True).filter(deleted=False).exclude(id=self.id)[:13]
        return cps
    def get_images(self):
        cps = CompanyProductOrServiceImage.objects.filter(company_product_or_service=self)
        return cps
    def get_related_products_services(self):
        cps = CompanyProductOrService.objects.filter(product_or_service=self.product_or_service).filter(active=True).filter(deleted=False).exclude(id=self.id)[:13]
        return cps
    def get_order_count(self):
        orders = Order.objects.filter(company_product_or_service=self).filter(active=True)
        quantity = 0
        for order in orders:
            quantity += order.quantity
        return quantity

class CompanyProductOrServiceImage(models.Model):
    company_product_or_service = models.ForeignKey(CompanyProductOrService, default=None)
    image = models.ImageField(upload_to='company_product-or-service/images',
                              verbose_name=_('CompanyProductOrServiceImage') ,max_length=500)

class ProductOrService(models.Model):
    id  = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    def __str__(self):
        return self.name

templates/profile/admin/admin_profile_page.html
{% extends 'profile_base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block head_container %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="{% static 'select2/select2-bootstrap.css' %}">
    <style>
        #add_new_product_or_service_div {
            display: none;
        }
    </style>
{% endblock %}


{% block base_container %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form id="" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">
                                    {{ profile_o.user.first_name }} {{ profile_o.user.last_name }}
                            </h4>
                        </div>
                        <div class="card-content">


                            <div class="row">
                                <label class="col-sm-2 label-on-left" for="id_is_active">{% trans 'is_active' %}</label>
                                <div class="col-sm-10" style="text-align: center;">
                                    <div class="checkbox pull-left">
                                        <label class="control-label">
                                            {{ admin_profile_form.is_active }}
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer text-center">
                                <input type="submit" class="btn btn-rose btn-fill" value="{% trans 'save_changes' %}"/>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'name' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>{{ profile_o.user.first_name }} {{ profile_o.user.last_name }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'photo' %}</label>
                                <div class="col-md-offset-2 col-md-4 col-sm-4">
                                    <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail">
                                            <img src="{% if profile_o.image %}{{ profile_o.image.url }}{% else %}{% static 'profile/assets/img/default-avatar.png' %}{% endif %}"
                                                 alt="...">
                                        </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'email' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ profile_o.user.email }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'voen' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ profile_o.voen }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'bank_account' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ profile_o.bank_account }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'region' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>{{ profile_o.region.name }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'address' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>

                                        <div>{{ profile_o.address }}</div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'businnes_type' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>
                                            {% for profile_o_businnes_type in profile_o.businnes_type.all %}
                                                <button class="btn btn-success btn-round">{{ profile_o_businnes_type.name }}</button>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'practices' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>

                                        <div>{{ profile_o.practices }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js_container %}
    {% if success_messages %}

        <script>
            $(document).ready(function () {
                swal({
                    title: "{% trans 'success' %}",
                    text: "{{ success_messages }}",
                    buttonsStyling: false,
                    confirmButtonClass: "btn btn-success",
                    type: "success"
                });
            });

        </script>

    {% endif %}
{% endblock %}

templates/profile/admin/admincompany_page.html
{% extends 'profile_base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load thumbnail %}
{% block head_container %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="{% static 'select2/select2-bootstrap.css' %}">
    <style>
        #add_new_product_or_service_div {
            display: none;
        }
    </style>
{% endblock %}


{% block base_container %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form id="" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h4 class="card-title">
                                {% if company %}
                                    {{ company.name }}
                                {% else %}
                                    {% trans 'add_new_company' %}
                                {% endif %}
                            </h4>
                        </div>
                        <div class="card-content">


                            <div class="row">
                                <label class="col-sm-2 label-on-left" for="id_is_active">{% trans 'is_active' %}</label>
                                <div class="col-sm-10" style="text-align: center;">
                                    <div class="checkbox pull-left">
                                        <label class="control-label">
                                            {{ admin_company_form.is_active }}
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer text-center">
                                <input type="submit" class="btn btn-rose btn-fill" value="{% trans 'save_changes' %}"/>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'name' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>{{ company.name }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'logo' %}</label>
                                <div class="col-md-offset-2 col-md-4 col-sm-4">
                                    <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail">
                                            <img src="


                                                    {% if company.logo %}{{ company.logo|thumbnail_url:'companies_list' }}{% else %}{% static 'profile/assets/img/image_placeholder.jpg' %}{% endif %}"
                                                 alt="...">
                                        </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'slogan' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>{{ company.slogan }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'email' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ company.email }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'voen' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ company.voen }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'bank_account' %}</label>
                                <div class="col-sm-6 ">
                                    <div class="form-group label-floating column-sizing">
                                        <label class="control-label"></label>
                                        <div>{{ company.bank_account }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'region' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>{{ company.region.name }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'address' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>

                                        <div>{{ company.address }}</div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'attachments' %}</label>
                                <div class="col-sm-8">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>
                                            {% for get_attachment in company.get_attachments %}
                                                <a class="btn btn-danger btn-round" href="{{ get_attachment.file.url }}" target="_blank">{% trans 'attachment' %} {{ forloop.counter }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'businnes_type' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>
                                        <div>
                                            {% for company_businnes_type in company.businnes_type.all %}
                                                <button class="btn btn-success btn-round">{{ company_businnes_type.name }}</button>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 label-on-left">{% trans 'practices' %}</label>
                                <div class="col-sm-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label"></label>

                                        <div>{{ company.practices }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js_container %}

    <script>
        $(document).ready(function () {

            {% if success_messages %}
                swal({
                    title: "{% trans 'success' %}",
                    text: "{% trans 'successfully_changed_company_detail' %}",
                    buttonsStyling: false,
                    confirmButtonClass: "btn btn-success",
                    type: "success"
                });
            {% endif %}
        });

    </script>

{% endblock %}